services:
  web:
    build:
      context: portfolio
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./portfolio/db:/db
    ports:
      - 8000:8000
    env_file:
      - portfolio/.env