services:
  web:
    build:
      context: portfolio
      dockerfile: Dockerfile.prod
    container_name: portfolio
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./portfolio/db:/db
      - ./portfolio/staticfiles:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - portfolio/.env
    environment:
      - DATABASE_PATH=/db/db.sqlite3
    restart: unless-stopped